# HTTPRoute for the authentication proxy service
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{.AuthProxyName}}-route
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .GatewayLabels}}
    {{$key}}: "{{$value}}"
    {{- end}}
spec:
  parentRefs:
  - name: {{.GatewayName}}
    namespace: "openshift-ingress"
    sectionName: "https"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/oauth2"
    backendRefs:
    - name: {{.AuthProxyName}}
      port: 8443
